### ISSUE TITLE
HGNC ID to ENSEMBL ID: connecting ASCT+B table Bgenes to this translation

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/hra-do-processor#12]
**From Red flag meeting on 8-18-2023:** 
"Bruce will add Ensembl IDs computationally during release process not to each ASCT+B table"

**Translating the ASCT+B table BGenes using HGNC IDs for genes to ENSEMBL IDs**
Josef's  HGNC-NR ontology already has both HGNC Ids and ESEMBL Ids https://bioportal.bioontology.org/ontologies/HGNC-NR
in dbxref relationship
Making sure it's easy to uptake this enrichment by outside consumers of ASCT+B table information through  hra-kg or hra-api. 
<img width="1001" alt="Screenshot 2023-09-01 at 5 06 19 PM" src="https://github.com/hubmapconsortium/hra-do-processor/assets/47257000/8b97681f-35b0-4ade-8b76-44b024a5bc06">

**Comment by bherr2** [comment]
@johardi can we enrich ASCT+B tables when they have HGNC IDs to pull in the db xrefs (if we don't already)?

**Comment by bherr2** [comment]
These are pulled in as part of enrichment
