### ISSUE TITLE
Fix LMHA owl file

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-do-processor#14]
The download link no longer exists for LMHA that is referenced here `https://github.com/hubmapconsortium/hra-do-processor/blob/main/scripts/download-ontologies.sh#L53`. Bioportal seems to have a comparable version here: <https://bioportal.bioontology.org/ontologies/LUNGMAP-HUMAN/?p=summary> but not sure if its the right one. If it is, setup the script to download from there instead.

**Comment by johardi** [comment]
Closed by https://github.com/hubmapconsortium/hra-do-processor/commit/06c55bb2992fe6fadf8091499269779624d5882a
