### ISSUE TITLE
Invalid terms on HRA-KG v2.0

### ISSUE THREAD

**Issue by johardi** [hubmapconsortium/hra-do-processor#16]
Here's the list:

| User input label | User input code | Why invalid? | Fix suggestion | Location |
| --- | --- | --- | --- | --- |
| ~CD34~ | HGNC:1662P28906 | Code error | HGNC:1662 | |
| lateral dorsal digital branch of radial nerve to index finger | FMA:44984 | Code not found | FMA:292936 | asct-b/peripheral-nervous-system |
| Cricothyroid | FMA46564 | Code error | FMA:46417 | ref-organ/asct-b-3d-models-crosswalk, ref-organ/united-female, ref-organ/united-male |
| branch of anterior interosseous nerve to flexor digitorum profundus | FMA:81216 | Code not found | -- | asct-b/peripheral-nervous-system |
| medial muscular branch of radial nerve to triceps brachii | FMA:81226 | Code not found | -- | asct-b/peripheral-nervous-system |
| lung bronchial submucosal gland | UBERON_8410043 | Code error | UBERON:8410043 | 2d-ftu/lung-bronchial-submucosal-gland |
| ciliated cell | LMHA:00142 | Code deprecated | CL:0000064 | asct-b/trachea |
| ~tracheal epithelial cell~ | LMHA:00583 | Code deprecated | CL:0000307 | |

**Comment by emquardokus** [comment]
tracheal epithelial cell was added to CL as CL:0000307

**Comment by emquardokus** [comment]
I can also find this one in FMA: branch of anterior interosseous nerve to flexor digitorum profundus 	FMA:81216 	Code not found 	-- 	asct-b/peripheral-n
<img width="789" alt="Screenshot 2023-12-15 at 2 40 41 PM" src="https://github.com/hubmapconsortium/hra-do-processor/assets/47257000/7d8859fe-20fc-48dd-89c9-1e521d31b92d">
ervous-system

**Comment by emquardokus** [comment]
**Cricothyroid 	FMA46564 	Code error 	FMA:46417 	ref-organ/asct-b-3d-models-crosswalk, ref-organ/united-female, ref-organ/united-male**
**Should be:**
Left cricothyroid muscle FMA:46564 http://purl.obolibrary.org/obo/FMA_46564

**Comment by emquardokus** [comment]
LMHA:00142. This is only showing up in the column header: CT/1/NOTES. The column labeled CT/1/ID is correct with CL ID CL:4033055
<img width="1358" alt="Screenshot 2023-12-15 at 3 37 48 PM" src="https://github.com/hubmapconsortium/hra-do-processor/assets/47257000/afb632dd-ab92-4cb8-815d-524e6ba29f9e">

**Comment by emquardokus** [comment]
FIXED: https://github.com/hubmapconsortium/ccf-releases/blob/main/rel-tools/2d-ftu-lookup.csv#L13 
lung bronchial submucosal gland 	UBERON_8410043 	Code error 	UBERON:8410043 	2d-ftu/lung-bronchial-submucosal-gland
